// Generated Data Model

export struct AppData {
    water-level: float,
    bean-level: float,
    water-temp: float,
    machine-status: string,
    grinder-status: string,
    current-strength: float,
    brew-strength: float,
    brew-temp: float,
    default-cup-size: string,
    auto-grind: bool,
    clean-reminder: bool,
    last-clean-date: string,
    total-brews: float,
    version: string,
}
